//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 商城百媚.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NewsID { get; set; }
        public string Title { get; set; }
        public string NTypes { get; set; }
        public string Content { get; set; }
        public string PhotoUrl { get; set; }
        public Nullable<System.DateTime> PushTime { get; set; }
        public Nullable<int> States { get; set; }
    }
}
